version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - npm run start
artifacts:
  files:
    - "**/*"
